// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQ2aqHEykwAuCj1Rn7w_1ASzbEO_GGJM',
    appId: '1:328047442108:web:0d8ad8ff63d8d5e5cb78b9',
    messagingSenderId: '328047442108',
    projectId: 'sugenix-b7093',
    authDomain: 'sugenix-b7093.firebaseapp.com',
    storageBucket: 'sugenix-b7093.firebasestorage.app',
    measurementId: 'G-0DLDE9CRSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfD83-8yAWnzaM0nt9igxb8k1Ynxws24Q',
    appId: '1:328047442108:android:2518684eb563f9aecb78b9',
    messagingSenderId: '328047442108',
    projectId: 'sugenix-b7093',
    storageBucket: 'sugenix-b7093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWiDjInLqwADp6FUGCjUXMMFVjt3a83Y',
    appId: '1:328047442108:ios:f98c90d17a0c2ba8cb78b9',
    messagingSenderId: '328047442108',
    projectId: 'sugenix-b7093',
    storageBucket: 'sugenix-b7093.firebasestorage.app',
    iosBundleId: 'com.example.sugenixMalabar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzWiDjInLqwADp6FUGCjUXMMFVjt3a83Y',
    appId: '1:328047442108:ios:f98c90d17a0c2ba8cb78b9',
    messagingSenderId: '328047442108',
    projectId: 'sugenix-b7093',
    storageBucket: 'sugenix-b7093.firebasestorage.app',
    iosBundleId: 'com.example.sugenixMalabar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYQ2aqHEykwAuCj1Rn7w_1ASzbEO_GGJM',
    appId: '1:328047442108:web:0327868431368b10cb78b9',
    messagingSenderId: '328047442108',
    projectId: 'sugenix-b7093',
    authDomain: 'sugenix-b7093.firebaseapp.com',
    storageBucket: 'sugenix-b7093.firebasestorage.app',
    measurementId: 'G-TTH1MXE3KG',
  );
}
